function constraints = signed_bigm_product(z, rho, delta, M)
%SIGNED_BIGM_PRODUCT Exact z = rho .* delta linearization.
%
% delta is binary and rho is a free continuous multiplier satisfying
% -M <= rho <= M. M may be scalar or conformable with rho.

constraints = [ ...
    -M <= rho, ...
    rho <= M, ...
    -M .* delta <= z, ...
    z <= M .* delta, ...
    rho - M .* (1 - delta) <= z, ...
    z <= rho + M .* (1 - delta)];
end
